### ISSUE TITLE
Issues raised in the morning session 

### ISSUE THREAD

**Issue by John-Kibirige** [tarikbouari/To-do-List#2]
## Issues raised 
congratulations @tarikbouari  upon making it this far with this project you did such a great job implementing the features that were stipulated, however, we managed to raise a few issues to make your code even better than it is 

- Kindly include the updated README.md as it is missing in your project and do not forget to include the webpack setup 
- Please also ensure that your webpack setup is sound and to achieve this I would recommend the following tutorial [https://www.youtube.com/watch?v=IZGNcSuwBZs&t=20s&ab_channel=TraversyMedia](https://www.youtube.com/watch?v=IZGNcSuwBZs&t=20s&ab_channel=TraversyMedia).
- If possible you could also do away with unused dependencies in your package.json file for example lodash and core-js as this will pile a lot of bundle size on your final project or app 
- You can as well put the following part of the code in a separate file and just import it to your project
 https://github.com/tarikbouari/To-do-List/blob/ff7a2fe4c72c500867015eb19f398ad9def27301/src/index.js#L29-L37

    This will be a reusable component that you can use and it will make your code neater and more organized.

- As a good practice it will also be good to store all none index.js files inside the src folder in their own folders as this will make your work even more organized

Other than that, we hope you finish everything on time, and happy coding 😄

**Comment by tarikbouari** [comment]
thanks for your review.
